version: '3.8'
services:
  php:
    image: php:8.1-apache
    container_name: miApp
    volumes:
      - ./app:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mariadb
    environment:  
      - MYSQL_HOST=mariadb
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: miApp
      MYSQL_USER:  ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      
